Os dados estão relacionados com campanhas de marketing direto de uma instituição bancária portuguesa. As campanhas de marketing foram baseadas em chamadas telefónicas. Muitas vezes, era necessário mais do que um contacto com o mesmo cliente, para se saber se o produto (depósito a prazo bancário) seria ('sim') ou não ('não') subscrito.

In [1]:
# Importando bibliotecas

import numpy             as np
import matplotlib.pyplot as plt
import pandas            as pd
import seaborn           as sns

pd.set_option('display.max_columns',None)
pd.set_option('display.max_rows', None)

In [2]:
# carregando a base de dados

df = pd.read_csv("/content/drive/MyDrive/PodAcademy/Tarefas/A0010_Bank_Marketing/bank-additional-full.csv", sep=";", encoding="ISO-8859-1" )

print(f' Quantidade de linhas: {df.shape[0]} \n Quantidade de colunas: {df.shape[1]}')

 Quantidade de linhas: 41188
 Quantidade de colunas: 21

In [3]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,261,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,149,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,226,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,151,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,307,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [4]:
df.tail()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,334,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,383,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,189,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,442,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,239,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [6]:
# Análise estatística para os dados numéricos

df.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [7]:
# Mapeamento target (0 = no, 1 = yes)
df_target = {'no': 0, 'yes': 1}

# Converter nomes para números
df['y'] = df['y'].map(df_target)

In [8]:
df.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,261,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,149,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
2,37,services,married,high.school,no,yes,no,telephone,may,mon,226,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,151,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
4,56,services,married,high.school,no,no,yes,telephone,may,mon,307,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0

## Data Preparation

In [9]:
abt = df.drop(columns=['y'])
target = df.y

abt.shape

(41188, 20)

In [10]:
target.head()

0    0
1    0
2    0
3    0
4    0
Name: y, dtype: int64

In [11]:
# Reservar 80% para treino e 20% para teste.

from sklearn.model_selection import train_test_split

# Dividindo o DataFrame em treino e teste
X_train, X_test, y_train, y_test = train_test_split(abt,target,test_size=0.2,random_state=42)

abt.shape,X_test.shape, X_train.shape

((41188, 20), (8238, 20), (32950, 20))

In [12]:
# Metadados

# Construindo função para obter metadados
def metadados(dataframe):
    """
    Gera um dataframe contendo metadados das colunas do dataframe fornecido.

    :dataframe: DataFrame para o qual os metadados serão gerados.
    :return: DataFrame contendo metadados.
    """

    # Coleta de metadados básicos
    metadata = pd.DataFrame({
        'nome_variavel': dataframe.columns,
        'tipo': dataframe.dtypes,
        'qt_nulos': dataframe.isnull().sum(),
        'percent_nulos': round((dataframe.isnull().sum() / len(dataframe))* 100,2),
        'cardinalidade': dataframe.nunique(),
    })
    metadata=metadata.sort_values(by='tipo',ascending=False)
    metadata = metadata.reset_index(drop=True)

    return metadata

In [13]:
# Obtendo metadados

metadados_df = metadados(abt)
metadados_df.head(100)

     nome_variavel     tipo  qt_nulos  percent_nulos  cardinalidade
0          marital   object         0            0.0              4
1        education   object         0            0.0              8
2          default   object         0            0.0              3
3          housing   object         0            0.0              3
4             loan   object         0            0.0              3
5          contact   object         0            0.0              2
6            month   object         0            0.0             10
7      day_of_week   object         0            0.0              5
8              job   object         0            0.0             12
9         poutcome   object         0            0.0              3
10     nr.employed  float64         0            0.0             11
11    emp.var.rate  float64         0            0.0             10
12       euribor3m  float64         0            0.0            316
13   cons.conf.idx  float64         0            0.0             26
14  cons.price.idx  float64         0            0.0             26
15             age    int64         0            0.0             78
16        previous    int64         0            0.0              8
17           pdays    int64         0            0.0             27
18        campaign    int64         0            0.0             42
19        duration    int64         0            0.0           1544

Pela análise do metadados acima verifica-se que não existem dados nulos.

In [14]:
#Padronização dos dados

from sklearn.preprocessing import StandardScaler

# Instanciando o scaler
scaler = StandardScaler()

# Selecionando colunas numéricas do conjunto de treino e teste
numeric_cols_train = X_train.select_dtypes(include=['float64', 'int64', 'int32']).columns
numeric_cols_test = X_test.select_dtypes(include=['float64', 'int64', 'int32']).columns

# Ajustando e transformando os dados de treino
X_train_scaled = X_train.copy()  # Copiar para preservar os dados originais
X_train_scaled[numeric_cols_train] = scaler.fit_transform(X_train[numeric_cols_train])

# Aplicando a transformação ao conjunto de teste
X_test_scaled = X_test.copy()  # Copiar para preservar os dados originais
X_test_scaled[numeric_cols_test] = scaler.transform(X_test[numeric_cols_test])


print(f'Colunas numéricas: {numeric_cols_train}')

Colunas numéricas: Index(['age', 'duration', 'campaign', 'pdays', 'previous', 'emp.var.rate',
       'cons.price.idx', 'cons.conf.idx', 'euribor3m', 'nr.employed'],
      dtype='object')

In [15]:
X_test_scaled.shape, X_train_scaled.shape

((8238, 20), (32950, 20))

In [16]:
X_train_scaled.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
12556,-0.001669,blue-collar,married,basic.9y,unknown,yes,no,telephone,jul,mon,-0.631114,-0.206242,0.194661,-0.350902,nonexistent,0.838794,0.589080,-0.472769,0.771354,0.843165
35451,-0.864095,admin.,married,university.degree,no,no,no,cellular,may,mon,-0.546321,0.513676,0.194661,-0.350902,nonexistent,-1.199440,-1.180760,-1.229916,-1.372028,-0.939748
30592,1.819007,retired,married,basic.4y,no,no,no,cellular,may,mon,-0.943306,1.233593,0.194661,1.677559,failure,-1.199440,-1.180760,-1.229916,-1.308581,-0.939748
17914,0.285806,housemaid,divorced,basic.9y,no,yes,no,cellular,jul,tue,-0.631114,0.873635,0.194661,-0.350902,nonexistent,0.838794,0.589080,-0.472769,0.771930,0.843165
3315,-0.097494,admin.,single,high.school,unknown,no,no,telephone,may,thu,0.332441,-0.206242,0.194661,-0.350902,nonexistent,0.647709,0.720307,0.890097,0.713674,0.330405

In [17]:
# Tratamento das vars. categóricas com baixa cardinalidade

#One Hot Encoding (Dummys)

from sklearn.preprocessing import OneHotEncoder

card_cutoff = 20
df_categ_onehot = metadados_df[(metadados_df['cardinalidade'] <= card_cutoff) & (metadados_df['tipo'] == 'object')]
lista_onehot = list(df_categ_onehot.nome_variavel.values)
print('Lista de vars para OneHot Encoding: ',lista_onehot)

Lista de vars para OneHot Encoding:  ['marital', 'education', 'default', 'housing', 'loan', 'contact', 'month', 'day_of_week', 'job', 'poutcome']

In [18]:

from sklearn.preprocessing import OneHotEncoder
import pandas as pd

# Instanciando o encoder
encoder = OneHotEncoder(drop='first', sparse_output=False)

# Aplicando o one-hot encoding ao conjunto de treino e teste
encoded_data_train = encoder.fit_transform(X_train_scaled[lista_onehot])
encoded_data_test = encoder.transform(X_test_scaled[lista_onehot])

# Criando DataFrames com as colunas codificadas
encoded_cols = encoder.get_feature_names_out(lista_onehot)

# Garantindo que o índice original seja preservado
encoded_df_train = pd.DataFrame(encoded_data_train, columns=encoded_cols, index=X_train_scaled.index)
encoded_df_test = pd.DataFrame(encoded_data_test, columns=encoded_cols, index=X_test_scaled.index)

# Concatenando os DataFrames codificados com os DataFrames originais
X_train_final = pd.concat(
    [X_train_scaled.drop(lista_onehot, axis=1), encoded_df_train], axis=1
).reset_index(drop=True)  # Reseta o índice para evitar inconsistências
X_test_final = pd.concat(
    [X_test_scaled.drop(lista_onehot, axis=1), encoded_df_test], axis=1
).reset_index(drop=True)  # Reseta o índice para evitar inconsistências

# Visualizando os dados processados do treino
X_train_final.head()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,marital_married,marital_single,marital_unknown,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,education_unknown,default_unknown,default_yes,housing_unknown,housing_yes,loan_unknown,loan_yes,contact_telephone,month_aug,month_dec,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown,poutcome_nonexistent,poutcome_success
0,-0.001669,-0.631114,-0.206242,0.194661,-0.350902,0.838794,0.589080,-0.472769,0.771354,0.843165,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,-0.864095,-0.546321,0.513676,0.194661,-0.350902,-1.199440,-1.180760,-1.229916,-1.372028,-0.939748,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1.819007,-0.943306,1.233593,0.194661,1.677559,-1.199440,-1.180760,-1.229916,-1.308581,-0.939748,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.285806,-0.631114,0.873635,0.194661,-0.350902,0.838794,0.589080,-0.472769,0.771930,0.843165,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,-0.097494,0.332441,-0.206242,0.194661,-0.350902,0.647709,0.720307,0.890097,0.713674,0.330405,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [19]:
X_train_final.shape, X_test_final.shape

((32950, 53), (8238, 53))

1. **Compondo a ABT tratada.**
    1. Trazendo o target para a tabela tratada.
    2. Fazemos o inner join para cruzar os índices das tabelas.

In [20]:
# Inner join usando o índice
abt_model_train = pd.merge(X_train_final, target, left_index=True, right_index=True, how='inner')
abt_model_train.shape

(32950, 54)

In [21]:
abt_model_test = pd.merge(X_test_final, target, left_index=True, right_index=True, how='inner')
abt_model_test.shape

(8238, 54)

In [22]:
abt_model_train.head()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,marital_married,marital_single,marital_unknown,education_basic.6y,education_basic.9y,education_high.school,education_illiterate,education_professional.course,education_university.degree,education_unknown,default_unknown,default_yes,housing_unknown,housing_yes,loan_unknown,loan_yes,contact_telephone,month_aug,month_dec,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,day_of_week_mon,day_of_week_thu,day_of_week_tue,day_of_week_wed,job_blue-collar,job_entrepreneur,job_housemaid,job_management,job_retired,job_self-employed,job_services,job_student,job_technician,job_unemployed,job_unknown,poutcome_nonexistent,poutcome_success,y
0,-0.001669,-0.631114,-0.206242,0.194661,-0.350902,0.838794,0.589080,-0.472769,0.771354,0.843165,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0
1,-0.864095,-0.546321,0.513676,0.194661,-0.350902,-1.199440,-1.180760,-1.229916,-1.372028,-0.939748,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0
2,1.819007,-0.943306,1.233593,0.194661,1.677559,-1.199440,-1.180760,-1.229916,-1.308581,-0.939748,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0
3,0.285806,-0.631114,0.873635,0.194661,-0.350902,0.838794,0.589080,-0.472769,0.771930,0.843165,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0
4,-0.097494,0.332441,-0.206242,0.194661,-0.350902,0.647709,0.720307,0.890097,0.713674,0.330405,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0

In [ ]:
abt_model_train.to_csv('/content/drive/MyDrive/PodAcademy/Tarefas/A0010_Bank_Marketing/bank_Marketing_abt_train.csv')

In [ ]:
abt_model_test.to_csv('/content/drive/MyDrive/PodAcademy/Tarefas/A0010_Bank_Marketing/bank_Marketing_abt_test.csv')